#!/usr/bin/env zsh

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

if which git >/dev/null 2>&1; then
    echo "[dotfiles] Fetching new files from git..."
    if git fetch; then
        git merge origin/master
        git submodule init
    else
        echo "[dotfiles] Fetching failed - no new files from master..."
    fi
else
    echo "[dotfiles] no git - no new files from master..."
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

